server:
  port: 8080

spring:
  application:
    name: bluebrain-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/blue_brain
    username: pravee08
    password: PraveeKan24*
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
application:
  security:
    jwt:
      secret-key: CT+HM5IOqC7/1ygQt8H41tYdQbZJDOimVuuTUsGT3U1k5V358M+sX5R1ZvVvNJNf
      expiration: 3600
      refresh-token:
          expiration: 3600
